services:
  guandan-scorer3:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - NODE_ENV=production
      - TZ=Pacific/Auckland
    restart: unless-stopped
