services:
  guandan-scorer3:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - VITE_SHOW_THEME_BUTTON=false
      - VITE_SHOW_RESET_BUTTON=false
    restart: unless-stopped
